package model.environment;

/**
 * The exception generated by a Organism who tries to exit the Environment.
 */
public class OutOfEnviromentException extends Exception {

    private static final long serialVersionUID = -4723076550396783510L;

}
